### ISSUE TITLE
Change `typing` state to `commenting`

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/hanghub#14]
We could also add to user states their emoticons as we have in the README. WDYT?

```
viewing 👀
commenting 💬
editing ✍
merging 🔀
idle 💨
```

**Comment by pjasiun** [comment]
👍 for "commenting" instead of "typing".

However, I am not sure about using emojis. They might be too distubing and do not fit well to the GitHub UI (there are no emojis used in other parts of GH UI).
