### ISSUE TITLE
View does not always return to the place

### ISSUE THREAD

**Issue by PatrykMiszczak** [ckeditor/hanghub#18]
It happened to me after submitting a review.

![Screenshot 2019-06-07 at 15 31 11](https://user-images.githubusercontent.com/829500/59108125-8260c800-893a-11e9-8f74-c6c367251310.png)
![Screenshot 2019-06-07 at 15 30 59](https://user-images.githubusercontent.com/829500/59108128-8260c800-893a-11e9-86c5-8010186f1bf6.png)

**Comment by oskarwrobel** [comment]
One more example https://github.com/ckeditor/hanghub/issues/20#issue-469467778

**Comment by ma2ciek** [comment]
The Github's DOM probably has changed and now the Hanghub layout is broken. Could you take a look on this one @elszczepano? I guess it should be easy to fix and to release a patched version.
