### ISSUE TITLE
Status is floating incorrectly

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/hanghub#20]
![Jul-17-2019 23-50-25](https://user-images.githubusercontent.com/1057056/61414527-7cbdb100-a8ee-11e9-9468-3c79b6a4ef1e.gif)

**Comment by kbkk** [comment]
#18 duplicate?

**Comment by oskarwrobel** [comment]
> #18 duplicate?

Yep. I'm closing this ticket.
