### ISSUE TITLE
Information about connected users moves to the next line on issue pages

### ISSUE THREAD

**Issue by elszczepano** [ckeditor/hanghub#26]
On issue pages in `gh-header-meta` element, there is an additional `div` element with `position-relative` right after the number of comments. For this reason, information about the number of connected users is moved to the next line. Removing this div should resolve the problem.

<img width="499" alt="Screenshot 2019-08-22 at 08 49 27" src="https://user-images.githubusercontent.com/23155008/63492529-e3b82200-c4b9-11e9-8ca6-8868335d2d76.png">

**Comment by ma2ciek** [comment]
That element might be on purpose :p It might be a new feature etc. Maybe it would be better to append our element after the `1 comment` instead of removing the extra div.

**Comment by ma2ciek** [comment]
Here we are: 

<img width="240" alt="Screen Shot 2019-08-23 at 13 03 55" src="https://user-images.githubusercontent.com/2768047/63588379-9cf42600-c5a6-11e9-9afb-b63a17a3a4e7.png">

Although, this was added as a span, before that div with `position: relative`, so this div is either an upcoming feature or it's a fix for some GH style problems.

**Comment by Reinmar** [comment]
It'd be nice to fix this because it makes the page to jump and looks bad.
