### ISSUE TITLE
The extension massively slows downs text editing when reviewing large PRs

### ISSUE THREAD

**Issue by oleq** [ckeditor/hanghub#30]
1.  Start reviewing some large PR.
2.  Start commenting on the code.
3.  Comment more and more (my impression is that the more you comment the worse it gets).
4.  Type a character in the comment.
5.  It takes 120ms to process the action which makes writing just insufferable.

![](https://user-images.githubusercontent.com/1099479/102110116-11567680-3e35-11eb-9641-b6ae916498dc.png)

I checked this and it looks like `_renderCollaboratorCounter` https://github.com/ckeditor/hanghub/blob/2f836e24fce998f7abad6e42f2213e51a119ecd9/frontend/src/HangHub.js#L168 gets executed many times on a single keypress and `querySelector` consumes a lot of time (this would explain why this feels bad with long reviews - the longer the diff, the more elements in DOM and the busier `querySelector` starts to get).

I put a logpoint in the method and this is how it looks:

![](https://user-images.githubusercontent.com/1099479/102110787-e1f43980-3e35-11eb-8642-924535151c21.gif)

**Comment by f1ames** [comment]
I can confirm it happens for me too (Chrome on Linux). I have recently noticed the same thing - significant delay for typing during reviews. First I thought it might be something wrong with my laptop, then started to blame GitHub itself then GH Writer (since the delay was visible while typing... sorry :sweat\_smile::speak\_no\_evil:).

I will disable the extensions and see if it gets better. Thx @oleq, you probably saved my a couple of precious minutes.

**Comment by czerwonkabartosz** [comment]
The same thing ... And I blamed GH Writer too :(

**Comment by oleq** [comment]
OK, some things to consider:

1.  At least in CKE5 team, this extension is mandatory.
2.  ...and that means that we need to get this fixed sooner or later.
3.  I don't know whose responsibility this is. 
    1.  I mean, I know there are contributors but I don't know who manages this project and who should schedule this issue and keep track of the progress.
    2.  Our KB does not have answers.

**Comment by f1ames** [comment]
May be related to #28 :thinking:

**Comment by czerwonkabartosz** [comment]
@elszczepano Could you look at this during the hackathon? ❤️  Please 🥃

**Comment by elszczepano** [comment]
Sure 👍🏻

**Comment by oleq** [comment]
![Sending Love GIF by memecandy](https://media2.giphy.com/media/UovX0xREM6pLOFtTCW/giphy.gif?cid=ecf05e475ve381sr2wl1ny4nazp2y8nnmn4bwhkyi8uto7d0&rid=giphy.gif)
